//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VCPassChanger.rc
//
#define IDR_MOUNT_TLB                   1
#define IDD_MOUNT_DLG                   101
#define IDD_PASSWORDCHANGE_DLG          102
#define IDB_DRIVEICON                   103
#define IDB_DRIVEICON_MASK              105
#define IDR_MENU                        106
#define IDR_MOUNT_RSRC_HEADER           109
#define IDS_UACSTRING                   110
#define IDB_LOGO_288DPI                 111
#define IDB_LOGO_96DPI                  112
#define IDB_SYS_DRIVEICON               113
#define IDB_SYS_DRIVEICON_MASK          114
#define IDC_VERIFY                      1002
#define IDC_OLD_PASSWORD                1004
#define IDC_NO_HISTORY                  1006
#define IDC_ENABLE_KEYFILES             1009
#define IDC_ENABLE_NEW_KEYFILES         1012
#define IDC_NEW_KEYFILES                1032
#define IDC_KEYFILES                    1033
#define IDC_VOLUME                      1034
#define IDC_PASSWORD                    1035
#define IDC_SELECT_DEVICE               1037
#define IDC_CREATE_VOLUME               1038
#define IDC_VOLUME_TOOLS                1039
#define IDC_WIPE_CACHE                  1040
#define IDC_MOUNTALL                    1041
#define IDC_SELECT_FILE                 1043
#define IDC_VOLUME_PROPERTIES           1045
#define IDT_VOLUME                      1051
#define IDT_PASSWORD                    1052
#define IDT_CURRENT                     1053
#define IDT_NEW                         1054
#define IDT_NEW_PASSWORD                1055
#define IDT_CONFIRM_PASSWORD            1056
#define IDC_EXIT                        1062
#define IDC_UNMOUNTALL                  1065
#define IDC_SHOW_PASSWORD_CHPWD_NEW     1081
#define IDC_SHOW_PASSWORD_CHPWD_ORI     1083
#define IDC_LOGO                        1098
#define IDT_NEW_PKCS5_PRF               1138
#define IDC_PKCS5_OLD_PRF_ID            1139
#define IDC_TRUECRYPT_MODE              1140
#define IDT_OLD_PIM                     1142
#define IDC_OLD_PIM                     1143
#define IDC_OLD_PIM_HELP                1144
#define IDC_NEW_PIM_ENABLE              1145
#define IDC_WIPE_MODE                   1152
#define IDT_WIPE_MODE                   1153
#define IDC_LOWER_BOX                   1170
#define IDM_HELP                        40001
#define IDM_ABOUT                       40002
#define IDM_UNMOUNT_VOLUME              40003
#define IDM_CLEAR_HISTORY               40004
#define IDM_BENCHMARK                   40005
#define IDM_TRAVELER                    40006
#define IDM_MOUNT_VOLUME_OPTIONS        40007
#define IDM_FAQ                         40008
#define IDM_REFRESH_DRIVE_LETTERS       40009
#define IDM_DEFAULT_KEYFILES            40010
#define IDM_WEBSITE                     40011
#define IDM_MOUNTALL                    40012
#define IDM_UNMOUNTALL                  40013
#define IDM_MOUNT_VOLUME                40014
#define IDM_CHANGE_PASSWORD             40015
#define IDM_VOLUME_WIZARD               40016
#define IDM_CREATE_VOLUME               40017
#define IDM_WIPE_CACHE                  40018
#define IDM_PREFERENCES                 40019
#define IDM_LICENSE                     40020
#define IDM_SELECT_FILE                 40021
#define IDM_SELECT_DEVICE               40022
#define IDM_VOLUME_PROPERTIES           40023
#define IDM_LANGUAGE                    40024
#define IDM_MOUNT_FAVORITE_VOLUMES      40025
#define IDM_BACKUP_VOL_HEADER           40026
#define IDM_RESTORE_VOL_HEADER          40027
#define IDM_HOTKEY_SETTINGS             40028
#define IDM_TC_DOWNLOADS                40029
#define IDM_NEWS                        40030
#define IDM_CONTACT                     40031
#define IDM_VERSION_HISTORY             40032
#define IDM_HOMEPAGE                    40033
#define IDM_TEST_VECTORS                40034
#define IDM_ADD_REMOVE_VOL_KEYFILES     40035
#define IDM_REMOVE_ALL_KEYFILES_FROM_VOL 40036
#define IDM_CHANGE_HEADER_KEY_DERIV_ALGO 40037
#define IDM_KEYFILE_GENERATOR           40038
#define IDM_ONLINE_TUTORIAL             40039
#define IDM_ONLINE_HELP                 40040
#define IDM_CHANGE_SYS_HEADER_KEY_DERIV_ALGO 40041
#define IDM_CHANGE_SYS_PASSWORD         40042
#define IDM_CREATE_RESCUE_DISK          40043
#define IDM_PERMANENTLY_DECRYPT_SYS     40044
#define IDM_VERIFY_RESCUE_DISK          40045
#define IDM_SYSTEM_ENCRYPTION_STATUS    40046
#define IDM_ENCRYPT_SYSTEM_DEVICE       40047
#define IDM_SYSENC_RESUME               40048
#define IDM_MOUNT_SYSENC_PART_WITHOUT_PBA 40049
#define IDM_CREATE_HIDDEN_OS            40050
#define IDM_TOKEN_PREFERENCES           40051
#define IDM_CLOSE_ALL_TOKEN_SESSIONS    40052
#define IDM_SYS_ENC_SETTINGS            40053
#define IDM_SYSENC_SETTINGS             40054
#define IDM_RESUME_INTERRUPTED_PROC     40055
#define IDM_MANAGE_TOKEN_KEYFILES       40056
#define IDM_SYS_FAVORITES_SETTINGS      40057
#define IDM_ORGANIZE_FAVORITES          40058
#define IDM_ORGANIZE_SYSTEM_FAVORITES   40059
#define IDM_ADD_VOLUME_TO_FAVORITES     40060
#define IDM_ADD_VOLUME_TO_SYSTEM_FAVORITES 40061
#define IDM_PERFORMANCE_SETTINGS        40062
#define IDM_ANALYZE_SYSTEM_CRASH        40063
#define IDM_DONATE                      40064
#define IDM_VOLUME_EXPANDER             40065
#define IDM_DEFAULT_MOUNT_PARAMETERS    40066
#define IDM_DECRYPT_NONSYS_VOL          40067
#define IDM_VERIFY_RESCUE_DISK_ISO      40068

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        120
#define _APS_NEXT_COMMAND_VALUE         40069
#define _APS_NEXT_CONTROL_VALUE         1179
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
