/*
 Derived from source code of TrueCrypt 7.1a, which is
 Copyright (c) 2008-2012 TrueCrypt Developers Association and which is governed
 by the TrueCrypt License 3.0.

 Modifications and additions to the original source code (contained in this file) 
 and all other portions of this file are Copyright (c) 2013-2017 IDRIX
 and are governed by the Apache License 2.0 the full text of which is
 contained in the file License.txt included in VeraCrypt binary and source
 code distribution packages.
*/

import "wtypes.idl";
import "..\Common\Password.h";

[
	uuid(9ACF6176-5FC4-4690-A025-B3306A50EB6A),
	helpstring("VeraCrypt Main UAC Support Library"),
	version(2.11)	// Update ComSetup.cpp when changing version number
]
library TrueCryptMainCom
{
	[
		uuid(C786E27C-2801-482c-B45D-D4357B270A29),
		object,
		oleautomation,
		helpstring("VeraCrypt Main UAC Support Interface")
	]
	interface ITrueCryptMainCom : IUnknown
	{
		void AnalyzeKernelMiniDump (__int64 hwndDlg);
		int BackupVolumeHeader (__int64 hwndDlg, BOOL bRequireConfirmation, BSTR lpszVolume);
		DWORD CallDriver (DWORD ioctl, BSTR input, BSTR *output);
		int ChangePassword (BSTR volumePath, Password *oldPassword, Password *newPassword, int pkcs5, int wipePassCount, __int64 hWnd);
		DWORD CopyFile (BSTR sourceFile, BSTR destinationFile);
		DWORD DeleteFile (BSTR file);
		BOOL IsPagingFileActive (BOOL checkNonWindowsPartitionsOnly);
		DWORD ReadWriteFile (BOOL write, BOOL device, BSTR filePath, BSTR *bufferBstr, unsigned __int64 offset, unsigned __int32 size, DWORD *sizeDone);
		DWORD RegisterFilterDriver (BOOL registerDriver, int filterType);
		DWORD RegisterSystemFavoritesService (BOOL registerService);
		int RestoreVolumeHeader (__int64 hwndDlg, BSTR lpszVolume);
		DWORD SetDriverServiceStartType (DWORD startType);
		DWORD WriteLocalMachineRegistryDwordValue (BSTR keyPath, BSTR valueName, DWORD value);
		int ChangePasswordEx (BSTR volumePath, Password *oldPassword, int old_pkcs5, Password *newPassword, int pkcs5, int wipePassCount, __int64 hWnd);
		int ChangePasswordEx2 (BSTR volumePath, Password *oldPassword, int old_pkcs5, BOOL truecryptMode, Password *newPassword, int pkcs5, int wipePassCount, __int64 hWnd);
		int ChangePasswordEx3 (BSTR volumePath, Password *oldPassword, int old_pkcs5, int old_pim, BOOL truecryptMode, Password *newPassword, int pkcs5, int pim, int wipePassCount, __int64 hWnd);
		DWORD GetFileSize (BSTR filePath, unsigned __int64* pSize);
		DWORD DeviceIoControl (BOOL readOnly, BOOL device, BSTR filePath, DWORD dwIoControlCode, BSTR input, BSTR *output);
		DWORD InstallEfiBootLoader (BOOL preserveUserConfig, BOOL hiddenOSCreation, int pim, int hashAlg);
		DWORD BackupEfiSystemLoader ();
		DWORD RestoreEfiSystemLoader ();
		DWORD GetEfiBootDeviceNumber (BSTR* pSdn);
		DWORD WriteEfiBootSectorUserConfig (DWORD userConfig, BSTR customUserMessage, int pim, int hashAlg);
		DWORD UpdateSetupConfigFile (BOOL bForInstall);
		DWORD GetSecureBootConfig (BOOL* pSecureBootEnabled, BOOL *pVeraCryptKeysLoaded);
	};

	[
		uuid(FE8B3B95-C80C-41f7-830F-FBA271C26F7E),
		helpstring("VeraCrypt Main UAC Support Coclass")
	]
	coclass TrueCryptMainCom
	{
		[default] interface ITrueCryptMainCom;
	}
}
